### ISSUE TITLE
Crashed when trying to remove a item from the queue

### ISSUE THREAD

**Issue by gangefors** [airdcnano/airdcnano#21]
[exceptioninfo.txt](https://github.com/airdcnano/airdcnano/files/89926/exceptioninfo.txt)

**Comment by maksis** [comment]
This project isn't maintained anymore. I'd suggest migrating to https://github.com/airdcpp-web/airdcpp-webclient/

**Comment by gangefors** [comment]
Ha! I should really try to read the README file again before continuing on a project I haven't looked at for over a year. Thanks for the tip. Time to set up a new docker image :)

**Comment by maksis** [comment]
I just updated the README a few minutes ago so you didn't really fail to notice anything
